### ISSUE TITLE
3.0.3

### ISSUE THREAD

**Issue by nguymi01** [ulfaslak/practical_data_science#4]
import requests as rq
query = "https://www.wikipedia.org/w/api.php?format=json&action=query&titles=Batman&prop=revisions&rvprop=content"
response = rq.get(query)
result = response.json()
print_dict_tree(result['query']['pages'])

#print(result['query']['pages']['4335']['pageid'])

#print(result['query']['pages']['4335']['ns'])

#print(result['query']['pages']['4335']['title'])
key = 0
for k in result['query']['pages']:
    key = k

print(result['query']['pages'][key]['revisions'][0]['*'])

**Comment by ulfaslak** [comment]
Good job! But Trang shared a one-line solution. No need to use a for loop to extract the key into a variable here :).
