### ISSUE TITLE
Exercise 3: Motivation behind extracting markup

### ISSUE THREAD

**Issue by mjprice23** [ulfaslak/practical_data_science#5]
I have a general question about extracting Wiki markup that can be applied more specifically to 3.1.2 and 3.2.1. What's the motivation behind extracting and downloading the markup as opposed to just downloading the response data in JSON format? Having the data in markup format is obviously easier for readability purposes, but it seems to me like having it in pure JSON makes it simple for keying into and extracting information like page length (like in 3.2.1). My understanding now is that we're making the query, receiving/converting it to JSON, and then extracting the data into markup format and saving it to the files that we'll then actually use to do our data analysis. Am I missing a part of this workflow, or a main way to easily extract fields from data in markup? Right now it seems like extracting just the markup removes the dict keys. Thanks in advance!

**Comment by ulfaslak** [comment]
It's a reasonable thing to wonder about. And actually you can complete the remainder of exercises in this course even if you save the pages in JSON format. But the reason for only keeping the markup is that everything **we need** is in there. Sure, you can get the page length from the JSON, but you can also just take the length of the markup string. SO we're just keeping what's essential, you see. And in general this is good practice, both for minding storage, but also just to make further processing steps simpler.

@katherinesmith23 shared a nice solution to get the markup. It's not *just* removing the keys.

```Python
list(data['query']['pages'].values())[0]['revisions'][0]['*']
```
