### ISSUE TITLE
4.1.1 Cutting off alliances_field after first alliance

### ISSUE THREAD

**Issue by WolffRuoff** [ulfaslak/practical_data_science#7]
The line below is currently only retrieving the first alliance in the function. It's unedited and I'm using it directly in exercise 4. When I print alliances_field and try it with Iron Man it just prints: "['| alliances = [[Avengers (comics)']" Please help!

```Python
alliances_field = re.findall(r"\| *alliances[\w\W]+?(?=\|.+=|\}\})", markup)

```

**Comment by ulfaslak** [comment]
That's super strange. I use the same regex in my own notebook and it works. I've tried on a couple of my students' computers and it also works. Which system are you on?

**Comment by WolffRuoff** [comment]
I'm on Windows 10. I asked Lucian and he didn't seem to know so he told me to post here. He said there was one person who had the problem last year.

**Comment by ulfaslak** [comment]
Likely, there is something up your native regular expression interpreter. Maybe it's outdated? I'm not an expert on stuff like this, so try and google something like "windows 10 python regex weird behavior"

**Comment by ulfaslak** [comment]
Did oyu figure this out? Looking closer at this, I think the problem may be inside the `(?=\|.+=|\}\})` part of the regex. This parenthesis is defining what the immediately previous `?` means. I.e. the regex is instructed to match instances of `\| *alliances[\w\W]+` and then stops when it sees `(?=\|.+=|\}\})`. Maybe the `|` operator works differently in your OS? Not sure, but that's my gut feeling.

**Comment by WolffRuoff** [comment]
Sorry just saw this. I fixed it by changing the line to
  `  alliances_field = re.findall(r"alliances.+?(?=.n\|)", markup)`

**Comment by ulfaslak** [comment]
Nice!
