### ISSUE TITLE
Not getting all characters with alliances in 4.1.4

### ISSUE THREAD

**Issue by leminhtrang99** [ulfaslak/practical_data_science#8]
### Issue summary
I seem to be having an issue with reading the files from the data folders. I think I do not have the correct number of characters with alliances to create the feature matrix. After traversing all three folders, I get a list of 892 characters; I double checked with someone else in the class and this number seems to fall short by around 150 characters.

This leads to inaccuracy with using the model for prediction in 4.4.1 because I do not have all the ambiguous characters (I noticed this when I was plotting the predictions for "heroness"). 

### This is my code for 4.1.4
```Python
#1
import numpy as np
alli_matrix = []
char_with_alli = []
factions = []

#Get all characters with alliances
for element in ["superheroes", "supervillains", "ambiguous"]:
    for direct in os.listdir("%s" % element):
        if not direct.startswith('.'):
            if len(get_alliances(direct.replace('.txt',''), element))!=0:
                char_with_alli.append(direct.replace('.txt',''))
                factions.append(element)

target_array = []

#Construct the alliance matrix and a target array to denote factions 
for element, faction in zip(char_with_alli, factions):
    alli_matrix.append(get_vector(element))
    if faction == "supervillains":
        target_array.append(0)
    elif faction == "superheroes":
        target_array.append(1)
    else:
        target_array.append(2)

#Create the data frame
import pandas as pd
data = pd.DataFrame(alli_matrix, index = char_with_alli, columns = all_teams)
data['faction'] = target_array

# Output
print(len(target_array))
print(len(char_with_alli))
print(len(alli_matrix))

892
892
892
```

**Comment by ulfaslak** [comment]
You have this line in there: `if len(get_alliances(direct.replace('.txt',''), element))!=0:`.

So you are only adding characters that have alliances. Which is why your numbers fall short.

**Comment by leminhtrang99** [comment]
The instruction in exercise 4.1.4 states to "not include characters that have no team alliances" (since we need to create an alliance matrix, there is no point in including characters that don't have alliances). The line of code I have is for filtering out characters that do not belong to any team alliances. I think even with that condition, however, my number of characters that do have alliances is still falling short.

**Comment by ulfaslak** [comment]
How do you know that?

**Comment by leminhtrang99** [comment]
In exercise 4.4.1, I noticed that have significantly fewer data points in the plot for "heroness" based on the alliance matrix of ambiguous characters compared to the plot you provided for that exercise (I did try to count and confirmed that I have 79, whereas your plot seems to have somewhere around 120 data points). The shape of my plot is also affected by the missing characters. I also cross checked the count of my character with a classmate and verified that I have fewer characters with alliances. 

Here is the image of my plot for 4.4.1

![download](https://user-images.githubusercontent.com/38641607/78260492-0688cb00-74cc-11ea-9247-470aed7fd618.png)

**Comment by leminhtrang99** [comment]
I finally realized the issue was coming from my dataset. I checked my folders against yours and realized many character files were missing. I'm not sure what happened to my dataset but I switched to using the same one as you and my results as well as the plot are now more accurate. Sorry for the confusion and thank you for answering my questions.

**Comment by ulfaslak** [comment]
No worries! Happy you figured it out.
